### ISSUE TITLE
issue build UMD in MPSoC zynqMP

### ISSUE THREAD

**Issue by dovanhuong** [LeiWang1999/ZYNQ-NVDLA#1]
hi @LeiWang1999 , I followed your instruction to build UMD for zynqMP, unfortunately, when I ported into zcu102 board, it appeared error as below: 
root@arm:/umd/out/apps/runtime/nvdla_runtime# ./nvdla_runtime
bash: ./nvdla_runtime: cannot execute binary file: Exec format error
root@arm:/umd/out/apps/runtime/nvdla_runtime#
If you have any suggestion, please share to me!
Thank you so much~

**Comment by LeiWang1999** [comment]
@dovanhuong libjpeg.a which under external folder should be built by yourself yet. you should build libjpeg9b.

**Comment by dovanhuong** [comment]
@LeiWang1999  do you mean I will re-build libjpeg.a? do you have the open source to build libjpeg9b? last time i just $sudo apt install libjpeg9b :((

**Comment by LeiWang1999** [comment]
@dovanhuong I think you should find the libjpeg.a under the lib you install by apt and replace the one under external

And, yes libjpeg is opensource and easy to build by oneself

**Comment by dovanhuong** [comment]
@LeiWang1999 Yesss expert. However, it have some errors when I compiled your repo as below: could you please take a look and help me some advice~
tony@dovanhuong:~/ZYNQ-NVDLA/umd$ make runtime TOOLCHAIN_PREFIX=/usr/bin/

for dir in core/src/runtime apps/runtime; do \
	make -C $dir; \
done
make[1]: Entering directory '/home/tony/ZYNQ-NVDLA/umd/core/src/runtime'
MODULE_CC /usr/bin/gcc
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/tony/ZYNQ-NVDLA/umd/core/src/runtime'
make[1]: Entering directory '/home/tony/ZYNQ-NVDLA/umd/apps/runtime'
MODULE_CC /usr/bin/gcc
compiling DlaImageUtils.cpp
/usr/bin/gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -g -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I/home/tony/ZYNQ-NVDLA/umd/external/libjpeg-turbo -I./include -I.  -c DlaImageUtils.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.o -MF /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.d -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.o
DlaImageUtils.cpp: In function ‘NvDlaError JPEG2DIMG(std::__cxx11::string, NvDlaImage*, nvdla::IRuntime::NvDlaTensor*)’:
DlaImageUtils.cpp:196:33: error: cannot convert ‘bool’ to ‘boolean’ for argument ‘2’ to ‘int jpeg_read_header(j_decompress_ptr, boolean)’
     jpeg_read_header(&info, true);
                                 ^
/home/tony/ZYNQ-NVDLA/umd/make/compile.mk:61: recipe for target '/home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.o' failed
make[1]: *** [/home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.o] Error 1
make[1]: Leaving directory '/home/tony/ZYNQ-NVDLA/umd/apps/runtime'
Makefile:43: recipe for target 'runtime' failed
make: *** [runtime] Error 2

**Comment by LeiWang1999** [comment]
.. I didnot have that issue

**Comment by LeiWang1999** [comment]
And for zynq MPSoc， I think you can use the offical prebuilt executable,

**Comment by LeiWang1999** [comment]
https://github.com/nvdla/sw/tree/master/prebuilt/arm64-linux

**Comment by dovanhuong** [comment]
@LeiWang1999 thank for your recommendation. I used to test with pre-built as you suggested. It has some error as below expert: 
root@smalldla:/arm64-linux# ls
aarch64_nvdla.lua    drm.ko               efi-virtio.rom       images               libnvdla_runtime.so  nvdla_runtime        opendla_1.ko         opendla_2.ko
root@smalldla:/arm64-linux# ./nvdla_runtime 
./nvdla_runtime: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
root@smalldla:/arm64-linux# 

If you have any advice or recommendation, I'm willing to hear from you~
Thank you so much and wish you will have a great thesis defense, cheer~~~

**Comment by dovanhuong** [comment]
@LeiWang1999 I completed fix error build with your repo, unfortunately. When I execute that file in board, it still have error as the first one :(((( 
tony@dovanhuong:~/ZYNQ-NVDLA/umd$ make runtime TOOLCHAIN_PREFIX=/usr/bin/

for dir in core/src/runtime apps/runtime; do \
	make -C $dir; \
done
make[1]: Entering directory '/home/tony/ZYNQ-NVDLA/umd/core/src/runtime'
MODULE_CC /usr/bin/gcc
compiling /home/tony/ZYNQ-NVDLA/umd/core/src/common/ErrorLogging.c
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c99 -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""   -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I. -c /home/tony/ZYNQ-NVDLA/umd/core/src/common/ErrorLogging.c -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/ErrorLogging.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/ErrorLogging.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/ErrorLogging.o
compiling /home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla.c
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c99 -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""   -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I. -c /home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla.c -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla.o
compiling /home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla_os.c
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c99 -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""   -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I. -c /home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla_os.c -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla_os.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla_os.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla_os.o
compiling /home/tony/ZYNQ-NVDLA/umd/core/src/common/Check.cpp
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I.  -c /home/tony/ZYNQ-NVDLA/umd/core/src/common/Check.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Check.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Check.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Check.o
compiling /home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterface.cpp
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I.  -c /home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterface.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterface.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterface.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterface.o
compiling /home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterfaceA.cpp
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I.  -c /home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterfaceA.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterfaceA.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterfaceA.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterfaceA.o
compiling /home/tony/ZYNQ-NVDLA/umd/core/src/common/Loadable.cpp
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I.  -c /home/tony/ZYNQ-NVDLA/umd/core/src/common/Loadable.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Loadable.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Loadable.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Loadable.o
compiling Emulator.cpp
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I.  -c Emulator.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Emulator.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Emulator.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Emulator.o
compiling Runtime.cpp
/usr/bin/gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/core/src/common/include -I/home/tony/ZYNQ-NVDLA/umd/port/linux/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I./include -I.  -c Runtime.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Runtime.o -MF /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Runtime.d -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Runtime.o
linking /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/libnvdla_runtime.mod.o
/usr/bin/ld -r /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/ErrorLogging.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/port/linux/nvdla_os.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Check.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterface.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/EMUInterfaceA.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime//home/tony/ZYNQ-NVDLA/umd/core/src/common/Loadable.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Emulator.o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/Runtime.o -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/libnvdla_runtime.mod.o
building /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/libnvdla_runtime.so
/usr/bin/g++ -shared /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/libnvdla_runtime.mod.o -o /home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime/libnvdla_runtime.so
make[1]: Leaving directory '/home/tony/ZYNQ-NVDLA/umd/core/src/runtime'
make[1]: Entering directory '/home/tony/ZYNQ-NVDLA/umd/apps/runtime'
MODULE_CC /usr/bin/gcc
compiling DlaImage.cpp
/usr/bin/gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -g -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I/home/tony/ZYNQ-NVDLA/umd/external/libjpeg-turbo -I./include -I.  -c DlaImage.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImage.o -MF /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImage.d -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImage.o
compiling DlaImageUtils.cpp
/usr/bin/gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -g -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I/home/tony/ZYNQ-NVDLA/umd/external/libjpeg-turbo -I./include -I.  -c DlaImageUtils.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.o -MF /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.d -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.o
compiling Server.cpp
/usr/bin/gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -g -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I/home/tony/ZYNQ-NVDLA/umd/external/libjpeg-turbo -I./include -I.  -c Server.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/Server.o -MF /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/Server.d -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/Server.o
In file included from Server.cpp:30:0:
RuntimeTest.h: In constructor ‘TestAppArgs::TestAppArgs()’:
RuntimeTest.h:58:13: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         mean{0.0, 0.0, 0.0, 0.0},
             ^
compiling RuntimeTest.cpp
/usr/bin/gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -g -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I/home/tony/ZYNQ-NVDLA/umd/external/libjpeg-turbo -I./include -I.  -c RuntimeTest.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/RuntimeTest.o -MF /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/RuntimeTest.d -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/RuntimeTest.o
In file included from RuntimeTest.cpp:31:0:
RuntimeTest.h: In constructor ‘TestAppArgs::TestAppArgs()’:
RuntimeTest.h:58:13: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         mean{0.0, 0.0, 0.0, 0.0},
             ^
compiling TestUtils.cpp
/usr/bin/gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -g -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I/home/tony/ZYNQ-NVDLA/umd/external/libjpeg-turbo -I./include -I.  -c TestUtils.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/TestUtils.o -MF /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/TestUtils.d -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/TestUtils.o
In file included from TestUtils.cpp:30:0:
RuntimeTest.h: In constructor ‘TestAppArgs::TestAppArgs()’:
RuntimeTest.h:58:13: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         mean{0.0, 0.0, 0.0, 0.0},
             ^
compiling main.cpp
/usr/bin/gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -g -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/tony/ZYNQ-NVDLA/umd/include -I/home/tony/ZYNQ-NVDLA/umd/core/include -I/home/tony/ZYNQ-NVDLA/umd/external/include -I/home/tony/ZYNQ-NVDLA/umd/external/libjpeg-turbo -I./include -I.  -c main.cpp -MD -MT /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/main.o -MF /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/main.d -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/main.o
In file included from main.cpp:30:0:
RuntimeTest.h: In constructor ‘TestAppArgs::TestAppArgs()’:
RuntimeTest.h:58:13: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         mean{0.0, 0.0, 0.0, 0.0},
             ^
linking /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/nvdla_runtime.mod.o
/usr/bin/ld -r /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImage.o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/DlaImageUtils.o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/Server.o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/RuntimeTest.o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/TestUtils.o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/main.o -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/nvdla_runtime.mod.o
building /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/nvdla_runtime
/usr/bin/g++ /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/nvdla_runtime.mod.o -pthread -L/home/tony/ZYNQ-NVDLA/umd/external/ -ljpeg -L/home/tony/ZYNQ-NVDLA/umd/out/core/src/runtime/libnvdla_runtime -lnvdla_runtime -o /home/tony/ZYNQ-NVDLA/umd/out/apps/runtime/nvdla_runtime/nvdla_runtime -Wl,-rpath=.
make[1]: Leaving directory '/home/tony/ZYNQ-NVDLA/umd/apps/runtime'
tony@dovanhuong:~/ZYNQ-NVDLA/umd$ 

Error in board: 
root@smalldla:/umd/out/apps/runtime/nvdla_runtime# ./nvdla_runtime 
-sh: ./nvdla_runtime: cannot execute binary file: Exec format error
root@smalldla:/umd/out/apps/runtime/nvdla_runtime# 

It is quite weired and confuse for me :(((

**Comment by LeiWang1999** [comment]
https://github.com/nvdla/sw/search?q=cannot+execute+binary+file&type=issues

**Comment by LeiWang1999** [comment]
Did you execute it on zynq MPSoc?

**Comment by dovanhuong** [comment]
yesss bro @LeiWang1999 ! I tried to execute in zcu102 board, the output like that :((( quite strange for me

**Comment by LeiWang1999** [comment]
.... it seems that you build it on your local machine but execute it on zynq , it is incorrect

**Comment by dovanhuong** [comment]
oh, so what is the correct way bro ?

**Comment by LeiWang1999** [comment]
make runtime all in arm.

**Comment by dovanhuong** [comment]
please wait bro~~~ @LeiWang1999 !! it have a problem when I make inside arm board, it appeared not have the make bash, could you please share to me how can you build the make inside zynq enviroment? thank you so much~~~

**Comment by LeiWang1999** [comment]
@dovanhuong  you should tranplant a Linux os on your zynq board.
Xilinx Petalinux is recommended.
And instruction was written in my blog...

**Comment by dovanhuong** [comment]
hello bro @LeiWang1999 ! I used translated to english from your blog and follow Ubuntu generated by you. Unfortunately, when I make it nothing happened right after as log below:
ubuntu@arm:/umd$ ls
apps  external            log.error  Makefile  utils
core  jpegsrc.v9d.tar.gz  make       port
ubuntu@arm:/umd$ export TOP=${PWD}
ubuntu@arm:/umd$ make runtime TOOLCHAIN_PREFIX=/usr/bin/
ubuntu@arm:/umd$ ls
apps  external            log.error  Makefile  utils
core  jpegsrc.v9d.tar.gz  make       port
ubuntu@arm:/umd$ 
 :((( therefore, I don't know which part I missed! warmly thank you so much~~
