### ISSUE TITLE
如何移植到 zcu 102 开发板上呢？

### ISSUE THREAD

**Issue by evanlee2021** [LeiWang1999/ZYNQ-NVDLA#10]
您好，我正在尝试在zcu102板卡上复现您的项目，但是在block design 的IP连接部分遇到了问题，我注意到您也将这个项目移植到zcu102上过，能麻烦大佬分享一下您的block design吗？ 感谢！！

**Comment by LeiWang1999** [comment]
@evanlee2021 您好，现在因为各种原因提供不了BD，但是除了我以外也有不少人在102上复现成功过，还是比较简单的。您现在是碰到了什么样的问题？

**Comment by evanlee2021** [comment]
> @evanlee2021 您好，现在因为各种原因提供不了BD，但是除了我以外也有不少人在102上复现成功过，还是比较简单的。您现在是碰到了什么样的问题？

因为刚刚接触这块，又急着复现成功，所以很多东西理解得比较浅显。目前的问题是移植到zcu102 的时候不知道如何配置ps以及进行block design，请问您是否方便与我们项目组进行合作呢？

**Comment by LeiWang1999** [comment]
@evanlee2021  你可以加我的微信，我帮你看一看，至于合作什么的可能要看我导师的意见。

my wechat id is wanglei199901.
