### ISSUE TITLE
kmd/zynq7000 与32位处理器的兼容

### ISSUE THREAD

**Issue by tongjiaxuan666** [LeiWang1999/ZYNQ-NVDLA#13]
1.nvdla/sw仓库中kmd是在64位处理器下运行的，kmd/zynq7000中都修改哪些函数去适配32位处理器呢？还有哪些函数需要修改才能在32位机器上正确运行呢？
2.在vp在编译生成的.nvdla文件可以在zynq7000上使用吗？

**Comment by tongjiaxuan666** [comment]
well done ！在zc706板卡上映射成功了，感谢题主！

**Comment by LeiWang1999** [comment]
@tongjiaxuan666 congrats!
