### ISSUE TITLE
Module not found when generating bitstream

### ISSUE THREAD

**Issue by xiaobeiyan** [LeiWang1999/ZYNQ-NVDLA#14]
Hi, I am facing the following problem when generating bitstream for ZC706:
![NVDLA-2022-02-08-17-10-39](https://user-images.githubusercontent.com/49969525/152955380-e94895ab-a82d-492a-afc7-6b9cfcbe1c2a.png)
It shows that [Synth 8-439] module 'CKLNQD12' not found.
Please help me solve these errors. Thanks a lot.

**Comment by LeiWang1999** [comment]
Clock gating is used to reduce power dissipation, but our FPGA doesn't need it, and to shutdown the clock gating circuit, you should add the following global definition:

VLIB_BYPASS_POWER_CG
NV_FPGA_FIFOGEN
FIFOGEN_MASTER_CLK_GATING_DISABLED
FPGA
SYNTHESIS

and as descirbed in this post: https://zhuanlan.zhihu.com/p/378202360

**Comment by xiaobeiyan** [comment]
This works. Thank you for your explanation.
