### ISSUE TITLE
Tengine的运行结果  Segmentation fault

### ISSUE THREAD

**Issue by yss-pku** [LeiWang1999/ZYNQ-NVDLA#16]
我用的是Tengine给的model_zoo里的   resnet18-cifar10_int8.tmfile  这个文件

运行 `./tm_classification_opendla -m /Tengine/models/resnet18-cifar10-int8.tmfile -i /Tengine/images/cat.jpg -g 32,32 -s 1,1,1`后

结果
![QQ截图20220301195752](https://user-images.githubusercontent.com/72870199/156165481-fa9fb8d0-6fe8-49a2-bf98-d08e33bb680c.png)

**Comment by LeiWang1999** [comment]
这好像是个bug,,,

**Comment by yss-pku** [comment]
> 

好吧，感谢解答！我看你的是直接就打印出了结果？我的前面要打印一大堆东西，要等好久

**Comment by WuZheng326** [comment]
请问还有后续吗？我也遇到了这个问题，后面有解决吗

**Comment by 3to11CHAINJ** [comment]
> 我用的是Tengine给的model_zoo里的 resnet18-cifar10_int8.tmfile 这个文件
> 
> 运行 `./tm_classification_opendla -m /Tengine/models/resnet18-cifar10-int8.tmfile -i /Tengine/images/cat.jpg -g 32,32 -s 1,1,1`后
> 
> 结果 ![QQ截图20220301195752](https://user-images.githubusercontent.com/72870199/156165481-fa9fb8d0-6fe8-49a2-bf98-d08e33bb680c.png)

我在推理resnet18-cifar10_int8.tmfile模型的时候也遇到了同样的问题，并且前面打印一大堆信息，请问后续解决了吗。
期待您的回复

**Comment by WuZheng326** [comment]
你好，我是吴峥，已收到您的邮件，我会尽快给您回复。
