### ISSUE TITLE
block design后implementation失败

### ISSUE THREAD

**Issue by Aleryaa** [LeiWang1999/ZYNQ-NVDLA#18]
您好，我使用ZC706开发板，按照您的博客现在已经完成了block design工作，现在想要继续生成比特流但对bd进行implementation会报错提示IO口数量不足。看您在知乎的回答说综合时的IO超标不影响后续设计，请问这个问题应该如何解决呢？或者说是我在block design的时候犯了什么错误导致了这个问题吗？
![ba2511a88fb93c43561c2301942e2c9](https://user-images.githubusercontent.com/75672502/165756922-140d796d-44bf-4b0f-bc28-78f535df0b5d.png)
![image](https://user-images.githubusercontent.com/75672502/165757068-457660b5-1f2e-456d-a753-30c13ae66f46.png)

**Comment by ChangAnGuLi** [comment]
我也遇到了同样的问题，请问您解决了吗

**Comment by Aleryaa** [comment]
> 我也遇到了同样的问题，请问您解决了吗

我给bd工程create HDL wrapper之后再impl似乎这个问题解决了，但是又遇到了新的问题，很头疼..

**Comment by ChangAnGuLi** [comment]
> > 我也遇到了同样的问题，请问您解决了吗
> 
> 我给bd工程create HDL wrapper之后再impl似乎这个问题解决了，但是又遇到了新的问题，很头疼..

我也遇到一个新的问题，您可以帮忙看下
![DR )J3184_`_VW6OY$24_75](https://user-images.githubusercontent.com/56307662/167978739-2a92e2ae-e0f3-4f9a-bd61-bd3051cdaf2f.png)
嘛

**Comment by Aleryaa** [comment]
> > > 我也遇到了同样的问题，请问您解决了吗
> > 
> > 
> > 我给bd工程create HDL wrapper之后再impl似乎这个问题解决了，但是又遇到了新的问题，很头疼..
> 
> 我也遇到一个新的问题，您可以帮忙看下 ![DR )J3184_`_VW6OY$24_75](https://user-images.githubusercontent.com/56307662/167978739-2a92e2ae-e0f3-4f9a-bd61-bd3051cdaf2f.png) 嘛

我遇到过这个问题，也还没有解决。不过我换了一个环境重新搭了一套工程再impl就变成了新的报错，可能和版本与环境有关系？

**Comment by ChangAnGuLi** [comment]
请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗

**Comment by ChangAnGuLi** [comment]
> 请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗

可能是我电脑的问题在虚拟机环境下impl就很容易闪退卡死

**Comment by Aleryaa** [comment]
> 请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗

我之前是在linux服务器端用vivado 2019.1出现了你这个问题，现在在windows端重新搭了一套，直接使用作者的RTL代码在vivado 2018.3 搭了一个工程，可以成功impl并生成bitstream，但是WNS和TNS为负，不知道会不会有什么问题。

**Comment by ChangAnGuLi** [comment]
> 

这样么，我等下试一下，谢谢

**Comment by ChangAnGuLi** [comment]
> > 请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗
> 
> 我之前是在linux服务器端用vivado 2019.1出现了你这个问题，现在在windows端重新搭了一套，直接使用作者的RTL代码在vivado 2018.3 搭了一个工程，可以成功impl并生成bitstream，但是WNS和TNS为负，不知道会不会有什么问题。

我试了好几个vivado版本都不行，您可以分享一下block design文件吗，我对照着看一下，是不是IP配置方面出了问题，我的zynq型号为XC7Z045FFG900-2I

**Comment by ChangAnGuLi** [comment]
> > > 请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗
> > 
> > 
> > 我之前是在linux服务器端用vivado 2019.1出现了你这个问题，现在在windows端重新搭了一套，直接使用作者的RTL代码在vivado 2018.3 搭了一个工程，可以成功impl并生成bitstream，但是WNS和TNS为负，不知道会不会有什么问题。
> 
> 我试了好几个vivado版本都不行，您可以分享一下block design文件吗，我对照着看一下，是不是IP配置方面出了问题，我的zynq型号为XC7Z045FFG900-2I

我修改implementation策略在opt_design中不勾选is_enable，可以正常完成整个implementation，但是在生成bit流文件时报错了

**Comment by ChangAnGuLi** [comment]
> > > 请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗
> > 
> > 
> > 我之前是在linux服务器端用vivado 2019.1出现了你这个问题，现在在windows端重新搭了一套，直接使用作者的RTL代码在vivado 2018.3 搭了一个工程，可以成功impl并生成bitstream，但是WNS和TNS为负，不知道会不会有什么问题。
> 
> 我试了好几个vivado版本都不行，您可以分享一下block design文件吗，我对照着看一下，是不是IP配置方面出了问题，我的zynq型号为XC7Z045FFG900-2I

我在nvdla issue里面找到了解决办法
![GZ 6 IALA@X~$5M7M8KS}QU](https://user-images.githubusercontent.com/56307662/168204907-153e3995-213e-4fc8-a82a-524413e277fe.png)
不过NV_small分支要怎么获取

**Comment by LeiWang1999** [comment]
@ChangAnGuLi 我的代码是直接用的docker里的，目测应该是master分支之前的某个版本

**Comment by Aleryaa** [comment]
> > > 请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗
> > 
> > 
> > 我之前是在linux服务器端用vivado 2019.1出现了你这个问题，现在在windows端重新搭了一套，直接使用作者的RTL代码在vivado 2018.3 搭了一个工程，可以成功impl并生成bitstream，但是WNS和TNS为负，不知道会不会有什么问题。
> 
> 我试了好几个vivado版本都不行，您可以分享一下block design文件吗，我对照着看一下，是不是IP配置方面出了问题，我的zynq型号为XC7Z045FFG900-2I

我今天重新试了一下用2019.1搭建工程，成功生成了比特流，意外的WNS和TNS也都是正常值。之前我也都是用的master分支生成的vmod代码，不知道是哪里出了问题...工程文件下载链接：https://drive.google.com/file/d/1Y4c3nsDzgxs-60ai1TgjPhkeOvmQuymj/view?usp=sharing

**Comment by ChangAnGuLi** [comment]
> > > > 请问您具体是怎么换的环境，我一开始是没有遇到这个问题的并且也是能够顺利输出bit流文件的，但是在现在的windows vivado2019.1环境下就不行了，难道真的要在Linux下复刻作者的步骤吗
> > > 
> > > 
> > > 我之前是在linux服务器端用vivado 2019.1出现了你这个问题，现在在windows端重新搭了一套，直接使用作者的RTL代码在vivado 2018.3 搭了一个工程，可以成功impl并生成bitstream，但是WNS和TNS为负，不知道会不会有什么问题。
> > 
> > 
> > 我试了好几个vivado版本都不行，您可以分享一下block design文件吗，我对照着看一下，是不是IP配置方面出了问题，我的zynq型号为XC7Z045FFG900-2I
> 
> 我今天重新试了一下用2019.1搭建工程，成功生成了比特流，意外的WNS和TNS也都是正常值。之前我也都是用的master分支生成的vmod代码，不知道是哪里出了问题...工程文件下载链接：https://drive.google.com/file/d/1Y4c3nsDzgxs-60ai1TgjPhkeOvmQuymj/view?usp=sharing

谢谢您，对比您的工程文件后我大致知道如何去修改我的设计了
