### ISSUE TITLE
implementation error [DRC INBB-3]

### ISSUE THREAD

**Issue by ChangAnGuLi** [LeiWang1999/ZYNQ-NVDLA#20]
您好@LeiWang1999，我最近有在向您学习NVDLA移植，开发板型号是XC7Z045FFG900-2I，在implementation时发生了如下错误
![77E9HN8RB4$M9XMBTZVV@PX](https://user-images.githubusercontent.com/56307662/168032628-74ada154-d2aa-4b31-8e0c-a1eeb019f485.png)
我一开始是可以正常implementation的，后来在依照开发板手册修改了一些ZYNQ IP配置之后就不能正常implementation了
考虑到可能是软件兼容性的问题，我在Ubuntu18.04下复现此过程不过仍然是同样的问题
希望您能给出一些修改意见，谢谢

**Comment by ChangAnGuLi** [comment]
我在NVDLA issue中找到了一个解决方案
![GZ 6 IALA@X~$5M7M8KS}QU](https://user-images.githubusercontent.com/56307662/168204273-02bba171-8918-4f8a-a448-3581e293544d.png)
那我应该怎么找到这vmod呢，用docker镜像生成的难道不是吗，希望您可以指导一下，您的博客说的是master分支的

**Comment by LeiWang1999** [comment]
在docker里生成文件，tmake那一步，生成的output文件夹里面的vmod(verlog module)，我是直接用的docker里的，没有用small分支

**Comment by ChangAnGuLi** [comment]
> 

我也是按照您的过程做的，但是上述这个问题您有遇到过吗，还是除了在block design中除了连线外还需要别的设置吗，对了，我的clock gating是如下图这样配置的，会不会是这里的问题
![)H3G{(8HS$D(2`%94F1R3~6](https://user-images.githubusercontent.com/56307662/168214124-8c7e2878-3a51-4fd2-90aa-f0317b7f51d2.png)

**Comment by ChangAnGuLi** [comment]
> 在docker里生成文件，tmake那一步，生成的output文件夹里面的vmod(verlog module)，我是直接用的docker里的，没有用small分支

您有遇到上述问题吗，您能否给出一些修改意见

**Comment by ChangAnGuLi** [comment]
问题已经解决

**Comment by ChangAnGuLi** [comment]
> 问题已经解决

软件适配问题

**Comment by H2OD** [comment]
> > 问题已经解决
> 
> 软件适配问题

想问一下是怎么解决的呀
