### ISSUE TITLE
Convert SD card boot to QSPI boot

### ISSUE THREAD

**Issue by ChangAnGuLi** [LeiWang1999/ZYNQ-NVDLA#21]
@LeiWang1999 需要对Petalinux设计做出哪些修改，QSPI flash只有256mb会不会不够用？
请问您有试过这样做吗，因为我选用的第三方开发板不能从SD卡启动，所以只能从QSPI启动，然后接下来的步骤要如何来做，您可以给出一些意见吗。
然后我现在是在SDK上把.bin和.elf给烧录到QSPI flash上面了，但是接下来要如何去完成linux系统的移植等问题呢？

**Comment by LeiWang1999** [comment]
肯定不够呀，你可以从FPGA上引出几个口，外接一个SD卡的扩展？
