### ISSUE TITLE
Error: nvdla_interface.h: No such file or directory

### ISSUE THREAD

**Issue by Wen-Sheng** [LeiWang1999/ZYNQ-NVDLA#23]
感谢你的无私的分享~
因为刚开始研究这部分
所以目前按照你的步骤一步一步执行
但是做到petalinux 的部份时，
遇到 "Error: nvdla_interface.h: No such file or directory"
不知道有没有解决的经验?
其实我有先在一般电脑上执行KMD的部分，
执行结果是没问题的，但是移植到peatliniux 上就出现这问题了.
环境是使用 petalinux 2020.2

**Comment by Wen-Sheng** [comment]
已解決了~

**Comment by 3to11CHAINJ** [comment]
> 

请问最后是怎么解决的，我也遇到了相同的问题，感谢！

**Comment by 3to11CHAINJ** [comment]
> 已解決了~
请问最后是怎么解决的，我也遇到了相同的问题，现在完全没有头绪，感谢！

**Comment by Wen-Sheng** [comment]
@3to11CHAINJ 
最后我是将原本的 #include <nvdla_interface.h> 改为 #include "nvdla_interface.h"
就找到档案了，但不确定这样修改会不会有问题，只知道compiler 能过....
