### ISSUE TITLE
Package IP Error

### ISSUE THREAD

**Issue by Alen302** [LeiWang1999/ZYNQ-NVDLA#6]
Appears when Package IP：
**[IP_Flow 19-3252] Bus Interface 'm_axi': The master AXIMM interface must have required port maps to the read or write channel signals.**
Does anyone know how to solve it？

**Comment by LeiWang1999** [comment]
Did you have some more detail about this issue? like a screenshot.

**Comment by Alen302** [comment]
![$CQFAC0405~43C}BVADN{HK](https://user-images.githubusercontent.com/84823360/132282917-47ab462f-26ac-453c-ae6b-c112996c5f76.png)

After automatically inferring the port：

![P~EBC{`F864W $Y4B9(KLS8](https://user-images.githubusercontent.com/84823360/132282982-d4ba64f0-ea0a-48b6-8e77-fd3310b4c5ac.png)

**Comment by LeiWang1999** [comment]
@liqx-github 你package axi协议线的时候，没有吧下面那些 nvdla_core2dbb*的信号线也加上去，这些也是axi总线的一部分。。。

**Comment by Alen302** [comment]
那请问我应该怎么做呢？(第一次弄这个，不太懂)

**Comment by Alen302** [comment]
是需要在自动推断之前设置些什么吗？还是得手动连接？

**Comment by Alen302** [comment]
是这样吗？
![X)_4 TS8Y I }37~E4TNPLL](https://user-images.githubusercontent.com/84823360/132289718-a08d491b-ceef-42bf-bec0-64606b538df2.png)
为什么在Memory Map的时候没有包装好的APB总线？
![QH4IIGO@7WC))N0P 6YO _M](https://user-images.githubusercontent.com/84823360/132290020-707c8449-6765-464c-905b-0aaf333382ae.png)

您能否帮忙用个人电脑试一下，看看是不是我自己的vivado版本的问题？
十分感谢！

**Comment by LeiWang1999** [comment]
@liqx-github 我试过，没有问题哎，Memory Map本来就是没有apb的，需要自己加一个，看我的tutorial

**Comment by Alen302** [comment]
再请问一下，上面那张图ports and interface那里，两个warning是可以不用管吗？我点自动推断的话就会变成一开始nvdla_core2dbb*的信号线没加上的情况

**Comment by LeiWang1999** [comment]
@liqx-github 嗯，是不用管的。
顺便问一下：考虑一下 给这个项目点个star & follow一下作者 吗？

**Comment by Alen302** [comment]
当然
