### ISSUE TITLE
PACKAGE IP 

### ISSUE THREAD

**Issue by mansemin** [LeiWang1999/ZYNQ-NVDLA#8]
1. Generate RTL code using tmake
2. Generate VIVADO project. ( ZCU102 Board ) 

![image](https://user-images.githubusercontent.com/58761432/137851523-00d74ebe-70eb-4813-89af-3b6d4653ef1f.png)

![image](https://user-images.githubusercontent.com/58761432/137851735-2e699c86-20fa-42c2-aa40-ef36103e8968.png)

  --> EVEN including manual RTL code NV_nvdla_wrapper.v. 
       The total number is 268 while your is 270 

3. Set top as NV_nvdla_wrapper.v. 
![image](https://user-images.githubusercontent.com/58761432/137851827-c2df3c93-ced1-4227-ba3a-070b533ac689.png)

4.  Create and Package NEW IP
![image](https://user-images.githubusercontent.com/58761432/137851895-ad867111-23fc-4138-b77a-57b4fe5551f2.png)

5. use first option as default 

![image](https://user-images.githubusercontent.com/58761432/137851951-2c504c41-4872-4f4d-a8fe-d4364db3fa1f.png)

6. ERROR OCCUR!

![image](https://user-images.githubusercontent.com/58761432/137851999-fe2bce5c-f06a-4b4d-84c5-4110704d7cb1.png)

 [IP_Flow 19-3252] Bus Interface 'm_axi': The master AXIMM interface must have required port maps to the read or write channel signals.

**Comment by LeiWang1999** [comment]
This issue was caused by abnormal ports’ name because when you packaged ip in some version of Vivado Suite it will detect if the signals of axi bus is aligned, and this was fixed, please pull the latest branch.

**Comment by mansemin** [comment]
- To fix this 
   1. pull lastest image from dokcer 
   2. download from github-page 

 When I try to method 2,  I find out some missing information .

 There is no error to open package IP. 

![image](https://user-images.githubusercontent.com/58761432/137860395-dcf07560-c9e1-491c-9a45-2f25a35dad44.png)


but 


![image](https://user-images.githubusercontent.com/58761432/137860607-e460a383-c152-4704-8a00-1e7128486667.png)


how to set IPs ?  I believe that I need two IPs 
 1. Master 
    - name: nvdal_core2dbb_ar
    
 2.  Slave 
   - name : interface_apb
    Like this 

  
![image](https://user-images.githubusercontent.com/58761432/137860841-7dc4a346-150b-4feb-826b-e77df73d4721.png)
 
   set Name and Mode 

   but how to set Port Mapping / Parameters .


  ( JUST make new project
    ADD RTL from github download RTL folder 
   Use. tools ->  Create and Package New IP ) 

![image](https://user-images.githubusercontent.com/58761432/137861274-083eea64-b246-4510-ae4e-3a4c3d801b19.png)

**Comment by evanlee2021** [comment]
hello, I also use zcu102 board ,but I don't know how to make block design ,can you share your block design? Thank you!
